# Ported from frontend/src/monsterSprites.js's MONSTER_SPRITES map (mechanically
# extracted, not hand-retyped, to avoid transcription drift). Cross-language
# duplicate is unavoidable here (Python backend can't import the JS module) —
# if the frontend sprite roster changes, re-run the same extraction and update
# this file. Only `src` and `fs` (frame size, when the sprite is an animated
# horizontal strip) are kept — `fs` is absent for static `type:'img'` sprites,
# which is exactly the cue /monster-image/{id} uses to decide whether to crop
# to frame 0 or serve the source image unmodified.
MONSTER_SPRITES = {
    'green_slime': {'src': '/sprites/monsters2/green_slime.png', 'fs': 32},
    'rat': {'src': '/sprites/monsters2/rat.png', 'fs': 32},
    'tiny_spider': {'src': '/sprites/monsters2/tiny_spider.png', 'fs': 32},
    'forest_imp': {'src': '/sprites/monsters2/forest_imp.png', 'fs': 32},
    'wisp': {'src': '/sprites/monsters2/wisp.png', 'fs': 32},
    'goblin': {'src': '/sprites/monsters2/goblin.png', 'fs': 32},
    'night_imp': {'src': '/sprites/monsters2/night_imp.png', 'fs': 32},
    'spectral_hound': {'src': '/sprites/monsters2/spectral_hound.png', 'fs': 32},
    'shadow_man': {'src': '/sprites/monsters2/shadow_man.png', 'fs': 32},
    'plaguebearer': {'src': '/sprites/monsters2/plaguebearer.png', 'fs': 32},
    'large_snake': {'src': '/sprites/monsters2/large_snake.png', 'fs': 32},
    'reaper': {'src': '/sprites/monsters2/reaper.png', 'fs': 32},
    'frost_yetling': {'src': '/sprites/monsters2/frost_yetling.png', 'fs': 32},
    'toxic_slime': {'src': '/sprites/monsters2/toxic_slime.png', 'fs': 32},
    'molten_golem': {'src': '/sprites/monsters2/molten_golem.png', 'fs': 32},
    'mirrorfiend': {'src': '/sprites/monsters2/mirrorfiend.png', 'fs': 32},
    'skeleton': {'src': '/sprites/monsters2/skeleton.png', 'fs': 32},
    'chaos_imp': {'src': '/sprites/monsters2/chaos_imp.png', 'fs': 32},
    'skeleton_warrior': {'src': '/sprites/monsters2/skeleton_warrior.png', 'fs': 32},
    'fire_elemental': {'src': '/sprites/monsters2/fire_elemental.png', 'fs': 32},
    'phantom_minotaur': {'src': '/sprites/monsters2/phantom_minotaur.png', 'fs': 48},
    'frost_golem': {'src': '/sprites/monsters2/frost_golem.png', 'fs': 48},
    'giant_spider': {'src': '/sprites/monsters2/giant_spider.png', 'fs': 64},
    'cave_troll': {'src': '/sprites/monsters2/cave_troll.png', 'fs': 64},
    'sandworm': {'src': '/sprites/monsters2/sandworm.png', 'fs': 32},
    'volcano_drake': {'src': '/sprites/monsters2/volcano_drake.png', 'fs': 64},
    'happy_blob': {'src': '/sprites/monsters2/happy_blob.png', 'fs': 64},
    'evil_shroom': {'src': '/sprites/monsters2/evil_shroom.png', 'fs': 32},
    'void_devil': {'src': '/sprites/monsters2/void_devil.png', 'fs': 32},
    'wild_buck': {'src': '/sprites/monsters2/wild_buck.png', 'fs': 48},
    'mimic': {'src': '/sprites/monsters2/mimic.png', 'fs': 48},
    'rock_golem': {'src': '/sprites/monsters2/rock_golem.png', 'fs': 48},
    'jrpg_ogre': {'src': '/sprites/monsters2/jrpg_ogre.png', 'fs': 48},
    'cave_bat': {'src': '/sprites/monsters2/cave_bat.png', 'fs': 64},
    'cyber_walker': {'src': '/sprites/monsters2/cyber_tooth.png', 'fs': 48},
    'cyber_drone': {'src': '/sprites/monsters2/cyber_drone.png', 'fs': 32},
    'flying_eye': {'src': '/sprites/monsters/mcf/flying_eye.png', 'fs': 150},
    'wild_goblin': {'src': '/sprites/monsters/mcf/goblin.png', 'fs': 150},
    'spore_beast': {'src': '/sprites/monsters/mcf/mushroom.png', 'fs': 150},
    'bone_walker': {'src': '/sprites/monsters/mcf/skeleton.png', 'fs': 150},
    'cursed_doll': {'src': '/sprites/monsters/st04/St-158_Cursed_Doll.png', 'fs': None},
    'toy_soldier': {'src': '/sprites/monsters/st04/St-151_Toy_Soldier.png', 'fs': None},
    'white_snake': {'src': '/sprites/monsters/st04/St-154_White_Snake.png', 'fs': None},
    'mad_hand': {'src': '/sprites/monsters/st04/St-157_Mad_Hand.png', 'fs': None},
    'mandrake': {'src': '/sprites/monsters/st04/St-156_Mandrake.png', 'fs': None},
    'cait_sith': {'src': '/sprites/monsters/st04/St-162_Cait_Sith.png', 'fs': None},
    'headless_chicken': {'src': '/sprites/monsters/st04/St-152_Headless_Chicken.png', 'fs': None},
    'dark_crow': {'src': '/sprites/monsters/st04/St-153_Dark_Crow.png', 'fs': None},
    'bugbear': {'src': '/sprites/monsters/st04/St-169_Bugbear.png', 'fs': None},
    'dead_soldier': {'src': '/sprites/monsters/st04/St-175_Dead_Soldier.png', 'fs': None},
    'nymph': {'src': '/sprites/monsters/st04/St-173_Nymph.png', 'fs': None},
    'arcane_soldieress': {'src': '/sprites/monsters/st04/St-182_Arcane_Soldieress.png', 'fs': None},
    'dullahan': {'src': '/sprites/monsters/st04/St-178_Dullahan.png', 'fs': None},
    'grave_robber': {'src': '/sprites/monsters/st04/St-161_Grave_Robber.png', 'fs': None},
    'evil_shaman': {'src': '/sprites/monsters/st04/St-177_Evil_Shaman.png', 'fs': None},
    'gravekeeper': {'src': '/sprites/monsters/st04/St-167_Gravekeeper.png', 'fs': None},
    'corpse_hound': {'src': '/sprites/monsters/st04/St-159_Corpse_Hound.png', 'fs': None},
    'gorgon': {'src': '/sprites/monsters/st04/St-172_Gorgon.png', 'fs': None},
    'jack_o_lantern': {'src': '/sprites/monsters/st04/St-155_Jack_O_Lantern.png', 'fs': None},
    'fanatic': {'src': '/sprites/monsters/st04/St-170_Fanatic.png', 'fs': None},
    'kelpie': {'src': '/sprites/monsters/st04/St-166_Kelpie.png', 'fs': None},
    'cursed_archer': {'src': '/sprites/monsters/st04/St-176_Cursed_Archer.png', 'fs': None},
    'arcane_cannon': {'src': '/sprites/monsters/st04/St-174_Arcane_Cannon.png', 'fs': None},
    'goat_man': {'src': '/sprites/monsters/st04/St-164_Goat_Man.png', 'fs': None},
    'hollow_soldier': {'src': '/sprites/monsters/st04/St-160_Hollow_Soldier.png', 'fs': None},
    'incubus': {'src': '/sprites/monsters/st04/St-171_Incubus.png', 'fs': None},
    'scarecrow': {'src': '/sprites/monsters/st04/St-163_Scarecrow.png', 'fs': None},
    'devil_well': {'src': '/sprites/monsters/st04/St-165_Devil_Well.png', 'fs': None},
    'death_machine': {'src': '/sprites/monsters/st04/St-184_Death_Machine.png', 'fs': None},
    'arcane_core': {'src': '/sprites/monsters/st04/St-181_Arcane_Core.png', 'fs': None},
    'machine_golem': {'src': '/sprites/monsters/st04/St-183_Machine_Golem.png', 'fs': None},
    'fallen_kingdom_knight': {'src': '/sprites/monsters/st04/St-189_Fallen_Kingdom_Knight.png', 'fs': None},
    'calamity_priest': {'src': '/sprites/monsters/st04/St-195_Calamity_Priest.png', 'fs': None},
    'royal_tomb_guardian': {'src': '/sprites/monsters/st04/St-194_Royal_Tomb_Guardian.png', 'fs': None},
    'judgement_soldier': {'src': '/sprites/monsters/st04/St-193_Judgement_Soldier.png', 'fs': None},
    'gem_thief': {'src': '/sprites/monsters/st04/St-191_Gem_Thief.png', 'fs': None},
    'cursed_king': {'src': '/sprites/monsters/st04/St-198_Cursed_King.png', 'fs': None},
    'evil_pudding': {'src': '/sprites/monsters/st04/St-179_Evil_Pudding.png', 'fs': None},
    'godblight_parasite': {'src': '/sprites/monsters/st04/St-180_Godblight_Parasite.png', 'fs': None},
    'dark_drake': {'src': '/sprites/monsters/st04/St-168_Drake.png', 'fs': None},
    'scylla': {'src': '/sprites/monsters/st04/St-185_Scylla.png', 'fs': None},
    'stone_troll': {'src': '/sprites/monsters/st04/St-186_Troll.png', 'fs': None},
    'fat_beast': {'src': '/sprites/monsters/st04/St-187_Fat_Beast.png', 'fs': None},
    'war_ogre': {'src': '/sprites/monsters/st04/St-188_Ogre.png', 'fs': None},
    'manticore': {'src': '/sprites/monsters/st04/St-190_Manticore.png', 'fs': None},
    'stone_colossus': {'src': '/sprites/monsters/st04/St-192_Stone_Colossus.png', 'fs': None},
    'divine_beast_young': {'src': '/sprites/monsters/st04/St-196_Divine_Beast_Young.png', 'fs': None},
    'divine_beast_adult': {'src': '/sprites/monsters/st04/St-197_Divine_Beast_Adult.png', 'fs': None},
    'cursed_king_second_form': {'src': '/sprites/monsters/st04/St-199_Cursed_King_Second_Form.png', 'fs': None},
    'divine_beast_perfect': {'src': '/sprites/monsters/st04/St-200_Divine_Beast_Perfect_Form.png', 'fs': None},
}
