# Ported verbatim from frontend/src/data.js's MONSTERS array (mechanically
# extracted, not hand-retyped, to avoid transcription drift). Cross-language
# duplicate is unavoidable here (Python backend can't import the JS module) —
# if the frontend roster changes, re-run the same extraction and update this file.
MONSTERS = [
    {'id': 'green_slime', 'name': 'Green Slime', 'adultHP': 7, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'rat', 'name': 'Sewer Rat', 'adultHP': 7, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'tiny_spider', 'name': 'Tiny Spider', 'adultHP': 8, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'forest_imp', 'name': 'Forest Imp', 'adultHP': 8, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'wisp', 'name': 'Wisp', 'adultHP': 8, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'evil_shroom', 'name': 'Evil Shroom', 'adultHP': 8, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'goblin', 'name': 'Goblin', 'adultHP': 9, 'kidHP': 6, 'atk': 3, 'gold': 8, 'kidGold': 5, 'tier': 2},
    {'id': 'night_imp', 'name': 'Night Imp', 'adultHP': 9, 'kidHP': 6, 'atk': 3, 'gold': 8, 'kidGold': 5, 'tier': 2},
    {'id': 'plaguebearer', 'name': 'Plaguebearer', 'adultHP': 9, 'kidHP': 6, 'atk': 3, 'gold': 8, 'kidGold': 5, 'tier': 2},
    {'id': 'spectral_hound', 'name': 'Spectral Hound', 'adultHP': 9, 'kidHP': 6, 'atk': 3, 'gold': 8, 'kidGold': 5, 'tier': 2},
    {'id': 'cave_bat', 'name': 'Cave Bat', 'adultHP': 10, 'kidHP': 7, 'atk': 3, 'gold': 9, 'kidGold': 5, 'tier': 2},
    {'id': 'shadow_man', 'name': 'Shadow Stalker', 'adultHP': 10, 'kidHP': 7, 'atk': 3, 'gold': 9, 'kidGold': 5, 'tier': 2},
    {'id': 'wild_buck', 'name': 'Wild Buck', 'adultHP': 10, 'kidHP': 7, 'atk': 3, 'gold': 9, 'kidGold': 5, 'tier': 2},
    {'id': 'skeleton', 'name': 'Skeleton', 'adultHP': 10, 'kidHP': 7, 'atk': 4, 'gold': 9, 'kidGold': 6, 'tier': 3},
    {'id': 'chaos_imp', 'name': 'Chaos Imp', 'adultHP': 10, 'kidHP': 7, 'atk': 4, 'gold': 9, 'kidGold': 6, 'tier': 3},
    {'id': 'large_snake', 'name': 'Giant Serpent', 'adultHP': 10, 'kidHP': 8, 'atk': 4, 'gold': 9, 'kidGold': 6, 'tier': 3},
    {'id': 'reaper', 'name': 'Grim Reaper', 'adultHP': 11, 'kidHP': 8, 'atk': 4, 'gold': 10, 'kidGold': 6, 'tier': 3},
    {'id': 'frost_yetling', 'name': 'Frost Yeti', 'adultHP': 11, 'kidHP': 8, 'atk': 4, 'gold': 10, 'kidGold': 6, 'tier': 3},
    {'id': 'toxic_slime', 'name': 'Toxic Slime', 'adultHP': 10, 'kidHP': 7, 'atk': 4, 'gold': 9, 'kidGold': 6, 'tier': 3},
    {'id': 'cyber_drone', 'name': 'Cyber Drone', 'adultHP': 10, 'kidHP': 7, 'atk': 4, 'gold': 9, 'kidGold': 6, 'tier': 3},
    {'id': 'void_devil', 'name': 'Void Devil', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'mimic', 'name': 'Mimic', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'skeleton_warrior', 'name': 'Skeleton Warrior', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'molten_golem', 'name': 'Molten Golem', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'mirrorfiend', 'name': 'Mirrorfiend', 'adultHP': 11, 'kidHP': 9, 'atk': 5, 'gold': 10, 'kidGold': 8, 'tier': 4},
    {'id': 'fire_elemental', 'name': 'Fire Elemental', 'adultHP': 12, 'kidHP': 9, 'atk': 5, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'phantom_minotaur', 'name': 'Phantom Minotaur', 'adultHP': 12, 'kidHP': 9, 'atk': 6, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'rock_golem', 'name': 'Rock Golem', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'cyber_walker', 'name': 'Cyber Tooth', 'adultHP': 12, 'kidHP': 9, 'atk': 6, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'frost_golem', 'name': 'Frost Golem', 'adultHP': 12, 'kidHP': 9, 'atk': 6, 'gold': 12, 'kidGold': 8, 'tier': 5},
    {'id': 'giant_spider', 'name': 'Giant Spider', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'cave_troll', 'name': 'Cave Troll', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'sandworm', 'name': 'Sandworm', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'jrpg_ogre', 'name': 'Ogre Chieftain', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'happy_blob', 'name': 'Elder Blob', 'adultHP': 12, 'kidHP': 9, 'atk': 6, 'gold': 12, 'kidGold': 8, 'tier': 5},
    {'id': 'volcano_drake', 'name': 'Volcano Drake', 'adultHP': 12, 'kidHP': 10, 'atk': 8, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'flying_eye', 'name': 'Flying Eye', 'adultHP': 9, 'kidHP': 6, 'atk': 3, 'gold': 8, 'kidGold': 5, 'tier': 2},
    {'id': 'wild_goblin', 'name': 'Wild Goblin', 'adultHP': 10, 'kidHP': 7, 'atk': 4, 'gold': 9, 'kidGold': 6, 'tier': 3},
    {'id': 'spore_beast', 'name': 'Spore Beast', 'adultHP': 8, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'bone_walker', 'name': 'Bone Walker', 'adultHP': 11, 'kidHP': 8, 'atk': 4, 'gold': 10, 'kidGold': 6, 'tier': 3},
    {'id': 'cursed_doll', 'name': 'Cursed Doll', 'adultHP': 7, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'toy_soldier', 'name': 'Toy Soldier', 'adultHP': 7, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'white_snake', 'name': 'White Snake', 'adultHP': 8, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'mad_hand', 'name': 'Mad Hand', 'adultHP': 7, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'mandrake', 'name': 'Mandrake', 'adultHP': 8, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'cait_sith', 'name': 'Cait Sith', 'adultHP': 8, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'headless_chicken', 'name': 'Headless Chicken', 'adultHP': 8, 'kidHP': 5, 'atk': 2, 'gold': 6, 'kidGold': 4, 'tier': 1},
    {'id': 'dark_crow', 'name': 'Dark Crow', 'adultHP': 9, 'kidHP': 6, 'atk': 3, 'gold': 8, 'kidGold': 5, 'tier': 2},
    {'id': 'bugbear', 'name': 'Bugbear', 'adultHP': 9, 'kidHP': 6, 'atk': 2, 'gold': 8, 'kidGold': 5, 'tier': 2},
    {'id': 'dead_soldier', 'name': 'Dead Soldier', 'adultHP': 9, 'kidHP': 6, 'atk': 3, 'gold': 8, 'kidGold': 5, 'tier': 2},
    {'id': 'nymph', 'name': 'Nymph', 'adultHP': 9, 'kidHP': 6, 'atk': 2, 'gold': 8, 'kidGold': 5, 'tier': 2},
    {'id': 'arcane_soldieress', 'name': 'Arcane Soldieress', 'adultHP': 10, 'kidHP': 7, 'atk': 3, 'gold': 9, 'kidGold': 5, 'tier': 2},
    {'id': 'dullahan', 'name': 'Dullahan', 'adultHP': 10, 'kidHP': 7, 'atk': 3, 'gold': 9, 'kidGold': 5, 'tier': 2},
    {'id': 'grave_robber', 'name': 'Grave Robber', 'adultHP': 10, 'kidHP': 7, 'atk': 3, 'gold': 9, 'kidGold': 5, 'tier': 2},
    {'id': 'evil_shaman', 'name': 'Evil Shaman', 'adultHP': 10, 'kidHP': 7, 'atk': 4, 'gold': 9, 'kidGold': 6, 'tier': 3},
    {'id': 'gravekeeper', 'name': 'Gravekeeper', 'adultHP': 10, 'kidHP': 7, 'atk': 3, 'gold': 9, 'kidGold': 5, 'tier': 2},
    {'id': 'corpse_hound', 'name': 'Corpse Hound', 'adultHP': 10, 'kidHP': 7, 'atk': 4, 'gold': 9, 'kidGold': 6, 'tier': 3},
    {'id': 'gorgon', 'name': 'Gorgon', 'adultHP': 11, 'kidHP': 8, 'atk': 4, 'gold': 10, 'kidGold': 6, 'tier': 3},
    {'id': 'jack_o_lantern', 'name': 'Jack O\'Lantern', 'adultHP': 11, 'kidHP': 8, 'atk': 4, 'gold': 10, 'kidGold': 6, 'tier': 3},
    {'id': 'fanatic', 'name': 'Fanatic', 'adultHP': 10, 'kidHP': 7, 'atk': 4, 'gold': 9, 'kidGold': 6, 'tier': 3},
    {'id': 'kelpie', 'name': 'Kelpie', 'adultHP': 11, 'kidHP': 8, 'atk': 4, 'gold': 10, 'kidGold': 6, 'tier': 3},
    {'id': 'cursed_archer', 'name': 'Cursed Archer', 'adultHP': 10, 'kidHP': 7, 'atk': 3, 'gold': 9, 'kidGold': 5, 'tier': 2},
    {'id': 'arcane_cannon', 'name': 'Arcane Cannon', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'goat_man', 'name': 'Goat Man', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'hollow_soldier', 'name': 'Hollow Soldier', 'adultHP': 12, 'kidHP': 9, 'atk': 5, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'incubus', 'name': 'Incubus', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'scarecrow', 'name': 'Scarecrow', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'devil_well', 'name': 'Devil Well', 'adultHP': 12, 'kidHP': 9, 'atk': 5, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'death_machine', 'name': 'Death Machine', 'adultHP': 12, 'kidHP': 9, 'atk': 5, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'arcane_core', 'name': 'Arcane Core', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'machine_golem', 'name': 'Machine Golem', 'adultHP': 12, 'kidHP': 9, 'atk': 5, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'fallen_kingdom_knight', 'name': 'Fallen Kingdom Knight', 'adultHP': 12, 'kidHP': 9, 'atk': 6, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'calamity_priest', 'name': 'Calamity Priest', 'adultHP': 12, 'kidHP': 9, 'atk': 5, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'royal_tomb_guardian', 'name': 'Royal Tomb Guardian', 'adultHP': 12, 'kidHP': 9, 'atk': 6, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'judgement_soldier', 'name': 'Judgement Soldier', 'adultHP': 12, 'kidHP': 9, 'atk': 5, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'gem_thief', 'name': 'Gem Thief', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'cursed_king', 'name': 'Cursed King', 'adultHP': 12, 'kidHP': 9, 'atk': 6, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'evil_pudding', 'name': 'Evil Pudding', 'adultHP': 11, 'kidHP': 8, 'atk': 5, 'gold': 10, 'kidGold': 7, 'tier': 4},
    {'id': 'godblight_parasite', 'name': 'Godblight Parasite', 'adultHP': 12, 'kidHP': 9, 'atk': 5, 'gold': 11, 'kidGold': 8, 'tier': 4},
    {'id': 'dark_drake', 'name': 'Dark Drake', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'scylla', 'name': 'Scylla', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'stone_troll', 'name': 'Stone Troll', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'fat_beast', 'name': 'Fat Beast', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'war_ogre', 'name': 'War Ogre', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'manticore', 'name': 'Manticore', 'adultHP': 12, 'kidHP': 10, 'atk': 8, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'stone_colossus', 'name': 'Stone Colossus', 'adultHP': 12, 'kidHP': 10, 'atk': 8, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'divine_beast_young', 'name': 'Divine Beast', 'adultHP': 12, 'kidHP': 10, 'atk': 7, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'divine_beast_adult', 'name': 'Divine Beast (Elder)', 'adultHP': 12, 'kidHP': 10, 'atk': 8, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'cursed_king_second_form', 'name': 'Cursed King (True Form)', 'adultHP': 12, 'kidHP': 10, 'atk': 8, 'gold': 12, 'kidGold': 9, 'tier': 5},
    {'id': 'divine_beast_perfect', 'name': 'Divine Beast (Perfect)', 'adultHP': 12, 'kidHP': 10, 'atk': 8, 'gold': 12, 'kidGold': 9, 'tier': 5},
]
